
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingTop: 32,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#3b4cca',
    textAlign: 'center',
    marginBottom: 28,
    letterSpacing: 1,
    textShadowColor: '#ffcb05',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    alignSelf: 'center',
  },
  shopCard: {
    width: 270,
    height: 450,
    borderRadius: 16,
    marginHorizontal: 18,
    marginVertical: 24,
    alignItems: 'center',
    justifyContent: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    padding: 12,
    backgroundColor: '#fafafa',
    borderWidth: 8,
    borderColor: '#ffcb05',
    overflow: 'hidden',
  },
  shopCardTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#222',
    textAlign: 'center',
    marginBottom: 12,
    letterSpacing: 1,
  },
  shopCardImageWrap: {
    width: 180,
    height: 180,
    backgroundColor: '#f0f0f0',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    marginTop: 8,
    borderWidth: 4,
    borderColor: '#3b4cca',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
    alignSelf: 'center',
  },
  shopCardImage: {
    width: 140,
    height: 140,
    resizeMode: 'contain',
  },
  shopCardDesc: {
    fontSize: 14,
    color: '#2a2a2a',
    textAlign: 'center',
    marginBottom: 12,
    minHeight: 40,
    backgroundColor: '#f5f5f5',
    padding: 8,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#ddd',
    width: '90%',
    alignSelf: 'center',
  },
  shopCardPriceWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    marginBottom: 12,
  },
  shopCardPrice: {
    fontSize: 32,
    color: '#e3350d',
    fontWeight: 'bold',
    marginLeft: 10,
  },
  shopCardAdd: {
    width: 270,
    height: 450,
    borderRadius: 28,
    marginHorizontal: 18,
    marginVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(200,200,200,0.5)',
    borderWidth: 2,
    borderColor: '#bbb',
  },
  shopCardAddIcon: {
    fontSize: 70,
    color: '#bbb',
    opacity: 0.6,
    marginBottom: 14,
  },
  shopCardAddText: {
    fontSize: 20,
    color: '#bbb',
    opacity: 0.7,
    fontWeight: 'bold',
  },
  error: {
    color: '#e3350d',
    textAlign: 'center',
    marginTop: 40,
    fontSize: 16,
  },
});

export default styles;
